# Generated by Django 2.2.16 on 2022-12-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221231_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='amount',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingridients',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Ingridient'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tag'),
        ),
    ]
